package com.jhondev.core.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity(name = "Usuarios")
@Table(name = "usuarios", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "correo"))
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String nombre;
	private String apellido;
	private String correo;
	private String pass;
	private Set<Encabezado> encabezados = new HashSet<Encabezado>(0);

	public Usuario() {
	}

	public Usuario(int id, String nombre, String apellido, String correo, String pass) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.correo = correo;
		this.pass = pass;
	}

	public Usuario(int id, String nombre, String apellido, String correo, String pass, Set<Encabezado> encabezados) {
		this.id = id;
		this.nombre = nombre;
		this.apellido = apellido;
		this.correo = correo;
		this.pass = pass;
		this.encabezados = encabezados;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "correo", unique = true, nullable = false)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "pass", nullable = false)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
//	public Set<Encabezado> getEncabezados() {
//		return this.encabezados;
//	}
//
//	public void setEncabezados(Set<Encabezado> encabezados) {
//		this.encabezados = encabezados;
//	}

}